name: careertalk
dependencies:
  - python=3.6
  - flask=1.0.2
  - sqlalchemy=1.2.0
  - pip=18.1
  - psycopg2==2.7.5
  - requests=2.21.0
  - pyopenssl=18.0.0
  - requests-oauthlib=1.0.0
  - oauth2client=4.1.2
  - google-api-python-client=1.7.4